import type { LevelSelectStats } from "./types";

/**
 * Per-level display bands for the DartBot level picker (D-M level-select
 * stats, `docs/superpowers/specs/2026-09-04-dartbot-level-select-stats-design.md`).
 * Generated by `dartbot-level-select-stats.ts` — each band is the
 * 25th/75th percentile from that script's simulation at the level.
 */
export const LEVEL_SELECT_STATS_TABLE: Readonly<
  Record<number, LevelSelectStats>
> = {
  1: { averageLow: 15, averageHigh: 36, checkoutLow: 0, checkoutHigh: 1 },
  2: { averageLow: 17, averageHigh: 40, checkoutLow: 1, checkoutHigh: 2 },
  3: { averageLow: 20, averageHigh: 43, checkoutLow: 2, checkoutHigh: 3 },
  4: { averageLow: 22, averageHigh: 45, checkoutLow: 3, checkoutHigh: 5 },
  5: { averageLow: 24, averageHigh: 55, checkoutLow: 5, checkoutHigh: 7 },
  6: { averageLow: 30, averageHigh: 60, checkoutLow: 8, checkoutHigh: 11 },
  7: { averageLow: 41, averageHigh: 76, checkoutLow: 12, checkoutHigh: 16 },
  8: { averageLow: 43, averageHigh: 95, checkoutLow: 17, checkoutHigh: 20 },
  9: { averageLow: 60, averageHigh: 100, checkoutLow: 26, checkoutHigh: 28 },
  10: { averageLow: 60, averageHigh: 100, checkoutLow: 31, checkoutHigh: 34 },
  11: { averageLow: 100, averageHigh: 140, checkoutLow: 46, checkoutHigh: 50 },
  12: { averageLow: 100, averageHigh: 140, checkoutLow: 58, checkoutHigh: 60 },
  13: { averageLow: 140, averageHigh: 180, checkoutLow: 70, checkoutHigh: 74 },
  14: { averageLow: 140, averageHigh: 180, checkoutLow: 85, checkoutHigh: 88 },
  15: { averageLow: 180, averageHigh: 180, checkoutLow: 96, checkoutHigh: 97 },
};

/**
 * The sole access point the UI calls. Returns the precomputed table today;
 * a future swap to a live DB lookup or on-the-fly compute changes only
 * this function's body — the per-level shape and every caller stay the
 * same.
 */
export function allLevelSelectStats(): Readonly<
  Record<number, LevelSelectStats>
> {
  return LEVEL_SELECT_STATS_TABLE;
}

/** Single-level lookup, clamped 1–15 (mirrors `skillProfileForLevel`). */
export function levelSelectStatsForLevel(level: number): LevelSelectStats {
  const clamped = Math.min(15, Math.max(1, Math.round(level)));
  const stats = LEVEL_SELECT_STATS_TABLE[clamped];
  if (!stats) {
    throw new Error(`No level-select stats for level ${clamped}`);
  }
  return stats;
}
