import type { LevelSelectStats } from "./types";

/**
 * Per-level display bands for the DartBot level picker (D-M level-select
 * stats, `docs/superpowers/specs/2026-09-04-dartbot-level-select-stats-design.md`).
 * Generated by `dartbot-level-select-stats.ts` — each band is the
 * 25th/75th percentile from that script's simulation at the level.
 */
export const LEVEL_SELECT_STATS_TABLE: Readonly<
  Record<number, LevelSelectStats>
> = {
  1: { averageLow: 20, averageHigh: 42, checkoutLow: 2, checkoutHigh: 3 },
  2: { averageLow: 21, averageHigh: 44, checkoutLow: 2, checkoutHigh: 4 },
  3: { averageLow: 22, averageHigh: 45, checkoutLow: 3, checkoutHigh: 5 },
  4: { averageLow: 24, averageHigh: 50, checkoutLow: 4, checkoutHigh: 7 },
  5: { averageLow: 26, averageHigh: 58, checkoutLow: 6, checkoutHigh: 9 },
  6: { averageLow: 30, averageHigh: 60, checkoutLow: 8, checkoutHigh: 11 },
  7: { averageLow: 36, averageHigh: 60, checkoutLow: 10, checkoutHigh: 14 },
  8: { averageLow: 41, averageHigh: 81, checkoutLow: 14, checkoutHigh: 17 },
  9: { averageLow: 45, averageHigh: 100, checkoutLow: 19, checkoutHigh: 23 },
  10: { averageLow: 60, averageHigh: 100, checkoutLow: 22, checkoutHigh: 25 },
  11: { averageLow: 60, averageHigh: 100, checkoutLow: 30, checkoutHigh: 33 },
  12: { averageLow: 60, averageHigh: 140, checkoutLow: 36, checkoutHigh: 39 },
  13: { averageLow: 100, averageHigh: 140, checkoutLow: 43, checkoutHigh: 46 },
  14: { averageLow: 100, averageHigh: 140, checkoutLow: 52, checkoutHigh: 55 },
  15: { averageLow: 100, averageHigh: 180, checkoutLow: 62, checkoutHigh: 65 },
};

/**
 * The sole access point the UI calls. Returns the precomputed table today;
 * a future swap to a live DB lookup or on-the-fly compute changes only
 * this function's body — the per-level shape and every caller stay the
 * same.
 */
export function allLevelSelectStats(): Readonly<
  Record<number, LevelSelectStats>
> {
  return LEVEL_SELECT_STATS_TABLE;
}

/** Single-level lookup, clamped 1–15 (mirrors `skillProfileForLevel`). */
export function levelSelectStatsForLevel(level: number): LevelSelectStats {
  const clamped = Math.min(15, Math.max(1, Math.round(level)));
  const stats = LEVEL_SELECT_STATS_TABLE[clamped];
  if (!stats) {
    throw new Error(`No level-select stats for level ${clamped}`);
  }
  return stats;
}
