import type { SkillProfile } from "./types";

/**
 * Per-level bot throw parameters (D-N, `08-DartBot.md`). `sigmaAlongMm`,
 * `sigmaAcrossMm`, `biasXMm`, `biasYMm` and `outlierRate` are calibrated
 * against level 1/6/15 anchors; the remaining fields are hand-set
 * independently of it.
 */
export const LEVEL_SKILL_TABLE: Readonly<Record<number, SkillProfile>> = {
  1: {
    sigmaAlongMm: 59.1,
    sigmaAcrossMm: 46.5,
    covarianceRotationDegrees: 0,
    biasXMm: 7.9,
    biasYMm: 10.6,
    outlierRate: 0.0096,
    outlierSigmaMm: 90,
    bedOffsetMm: 3.0,
    bounceOutRate: 0.05,
    deflectionRadiusMm: 12,
    decisionQuality: 7,
  },
  2: {
    sigmaAlongMm: 51.1,
    sigmaAcrossMm: 39.6,
    covarianceRotationDegrees: 0,
    biasXMm: 5.9,
    biasYMm: 8.3,
    outlierRate: 0.0071,
    outlierSigmaMm: 85,
    bedOffsetMm: 2.7,
    bounceOutRate: 0.045,
    deflectionRadiusMm: 12,
    decisionQuality: 13,
  },
  3: {
    sigmaAlongMm: 43.6,
    sigmaAcrossMm: 33.2,
    covarianceRotationDegrees: 0,
    biasXMm: 5.6,
    biasYMm: 6.7,
    outlierRate: 0.0059,
    outlierSigmaMm: 80,
    bedOffsetMm: 2.4,
    bounceOutRate: 0.04,
    deflectionRadiusMm: 11,
    decisionQuality: 20,
  },
  4: {
    sigmaAlongMm: 36.4,
    sigmaAcrossMm: 28.6,
    covarianceRotationDegrees: 0,
    biasXMm: 4.3,
    biasYMm: 6.5,
    outlierRate: 0.0048,
    outlierSigmaMm: 75,
    bedOffsetMm: 2.1,
    bounceOutRate: 0.035,
    deflectionRadiusMm: 11,
    decisionQuality: 27,
  },
  5: {
    sigmaAlongMm: 31.9,
    sigmaAcrossMm: 24.2,
    covarianceRotationDegrees: 0,
    biasXMm: 4.1,
    biasYMm: 5.1,
    outlierRate: 0.0039,
    outlierSigmaMm: 70,
    bedOffsetMm: 1.8,
    bounceOutRate: 0.03,
    deflectionRadiusMm: 10,
    decisionQuality: 33,
  },
  6: {
    sigmaAlongMm: 27.5,
    sigmaAcrossMm: 20.1,
    covarianceRotationDegrees: 0,
    biasXMm: -5.0,
    biasYMm: 3.1,
    outlierRate: 0.003,
    outlierSigmaMm: 65,
    bedOffsetMm: 1.6,
    bounceOutRate: 0.028,
    deflectionRadiusMm: 10,
    decisionQuality: 40,
  },
  7: {
    sigmaAlongMm: 23.1,
    sigmaAcrossMm: 17.4,
    covarianceRotationDegrees: 0,
    biasXMm: 2.5,
    biasYMm: 3.3,
    outlierRate: 0.0026,
    outlierSigmaMm: 60,
    bedOffsetMm: 1.4,
    bounceOutRate: 0.025,
    deflectionRadiusMm: 9,
    decisionQuality: 47,
  },
  8: {
    sigmaAlongMm: 18.9,
    sigmaAcrossMm: 14.8,
    covarianceRotationDegrees: 0,
    biasXMm: 2.5,
    biasYMm: 3.3,
    outlierRate: 0.0022,
    outlierSigmaMm: 55,
    bedOffsetMm: 1.2,
    bounceOutRate: 0.022,
    deflectionRadiusMm: 9,
    decisionQuality: 53,
  },
  9: {
    sigmaAlongMm: 15.0,
    sigmaAcrossMm: 12.4,
    covarianceRotationDegrees: 0,
    biasXMm: 1.2,
    biasYMm: 1.7,
    outlierRate: 0.0018,
    outlierSigmaMm: 50,
    bedOffsetMm: 1.0,
    bounceOutRate: 0.02,
    deflectionRadiusMm: 8,
    decisionQuality: 60,
  },
  10: {
    sigmaAlongMm: 13.3,
    sigmaAcrossMm: 10.1,
    covarianceRotationDegrees: 0,
    biasXMm: 1.2,
    biasYMm: 1.7,
    outlierRate: 0.0015,
    outlierSigmaMm: 48,
    bedOffsetMm: 0.9,
    bounceOutRate: 0.018,
    deflectionRadiusMm: 8,
    decisionQuality: 67,
  },
  11: {
    sigmaAlongMm: 9.9,
    sigmaAcrossMm: 8.1,
    covarianceRotationDegrees: 0,
    biasXMm: 0.9,
    biasYMm: 0.9,
    outlierRate: 0.0012,
    outlierSigmaMm: 45,
    bedOffsetMm: 0.7,
    bounceOutRate: 0.015,
    deflectionRadiusMm: 7,
    decisionQuality: 73,
  },
  12: {
    sigmaAlongMm: 8.4,
    sigmaAcrossMm: 6.2,
    covarianceRotationDegrees: 0,
    biasXMm: 0.4,
    biasYMm: 0.7,
    outlierRate: 0.0009,
    outlierSigmaMm: 42,
    bedOffsetMm: 0.6,
    bounceOutRate: 0.013,
    deflectionRadiusMm: 7,
    decisionQuality: 80,
  },
  13: {
    sigmaAlongMm: 6.9,
    sigmaAcrossMm: 5.2,
    covarianceRotationDegrees: 0,
    biasXMm: 0.4,
    biasYMm: 0.7,
    outlierRate: 0.0007,
    outlierSigmaMm: 40,
    bedOffsetMm: 0.5,
    bounceOutRate: 0.011,
    deflectionRadiusMm: 6,
    decisionQuality: 87,
  },
  14: {
    sigmaAlongMm: 5.6,
    sigmaAcrossMm: 3.6,
    covarianceRotationDegrees: 0,
    biasXMm: 0.3,
    biasYMm: 0.3,
    outlierRate: 0.0004,
    outlierSigmaMm: 38,
    bedOffsetMm: 0.4,
    bounceOutRate: 0.009,
    deflectionRadiusMm: 6,
    decisionQuality: 93,
  },
  15: {
    sigmaAlongMm: 4.4,
    sigmaAcrossMm: 3.0,
    covarianceRotationDegrees: 0,
    biasXMm: 0,
    biasYMm: 0.2,
    outlierRate: 0.0002,
    outlierSigmaMm: 35,
    bedOffsetMm: 0.3,
    bounceOutRate: 0.007,
    deflectionRadiusMm: 5,
    decisionQuality: 100,
  },
};

export function skillProfileForLevel(level: number): SkillProfile {
  const clamped = Math.min(15, Math.max(1, Math.round(level)));
  const profile = LEVEL_SKILL_TABLE[clamped];
  if (!profile) {
    throw new Error(`No skill profile for level ${clamped}`);
  }
  return profile;
}
