import type { SkillProfile } from "./types";

/**
 * Per-level bot throw parameters (D-L, `08-DartBot.md`). `sigmaAlongMm`,
 * `sigmaAcrossMm`, `biasXMm`, `biasYMm` and `outlierRate` are calibrated
 * against a measured population prior; the remaining fields are hand-set
 * independently of it.
 */
export const LEVEL_SKILL_TABLE: Readonly<Record<number, SkillProfile>> = {
  1: {
    sigmaAlongMm: 91.8,
    sigmaAcrossMm: 72.3,
    covarianceRotationDegrees: 0,
    biasXMm: 12.3,
    biasYMm: 16.4,
    outlierRate: 0.0149,
    outlierSigmaMm: 90,
    bedOffsetMm: 3.0,
    bounceOutRate: 0.05,
    deflectionRadiusMm: 12,
    decisionQuality: 7,
  },
  2: {
    sigmaAlongMm: 73.1,
    sigmaAcrossMm: 56.6,
    covarianceRotationDegrees: 0,
    biasXMm: 8.4,
    biasYMm: 11.8,
    outlierRate: 0.0098,
    outlierSigmaMm: 85,
    bedOffsetMm: 2.7,
    bounceOutRate: 0.045,
    deflectionRadiusMm: 12,
    decisionQuality: 13,
  },
  3: {
    sigmaAlongMm: 56.8,
    sigmaAcrossMm: 43.1,
    covarianceRotationDegrees: 0,
    biasXMm: 7.4,
    biasYMm: 8.9,
    outlierRate: 0.0077,
    outlierSigmaMm: 80,
    bedOffsetMm: 2.4,
    bounceOutRate: 0.04,
    deflectionRadiusMm: 11,
    decisionQuality: 20,
  },
  4: {
    sigmaAlongMm: 42.8,
    sigmaAcrossMm: 34.4,
    covarianceRotationDegrees: 0,
    biasXMm: 5.3,
    biasYMm: 8.0,
    outlierRate: 0.0058,
    outlierSigmaMm: 75,
    bedOffsetMm: 2.1,
    bounceOutRate: 0.035,
    deflectionRadiusMm: 11,
    decisionQuality: 27,
  },
  5: {
    sigmaAlongMm: 34.7,
    sigmaAcrossMm: 26.7,
    covarianceRotationDegrees: 0,
    biasXMm: 4.6,
    biasYMm: 5.7,
    outlierRate: 0.0043,
    outlierSigmaMm: 70,
    bedOffsetMm: 1.8,
    bounceOutRate: 0.03,
    deflectionRadiusMm: 10,
    decisionQuality: 33,
  },
  6: {
    sigmaAlongMm: 27.5,
    sigmaAcrossMm: 20.1,
    covarianceRotationDegrees: 0,
    biasXMm: -5.0,
    biasYMm: 3.1,
    outlierRate: 0.003,
    outlierSigmaMm: 65,
    bedOffsetMm: 1.6,
    bounceOutRate: 0.028,
    deflectionRadiusMm: 10,
    decisionQuality: 40,
  },
  7: {
    sigmaAlongMm: 21.3,
    sigmaAcrossMm: 16.3,
    covarianceRotationDegrees: 0,
    biasXMm: 2.5,
    biasYMm: 3.3,
    outlierRate: 0.0025,
    outlierSigmaMm: 60,
    bedOffsetMm: 1.4,
    bounceOutRate: 0.025,
    deflectionRadiusMm: 9,
    decisionQuality: 47,
  },
  8: {
    sigmaAlongMm: 15.9,
    sigmaAcrossMm: 12.9,
    covarianceRotationDegrees: 0,
    biasXMm: 2.5,
    biasYMm: 3.3,
    outlierRate: 0.002,
    outlierSigmaMm: 55,
    bedOffsetMm: 1.2,
    bounceOutRate: 0.022,
    deflectionRadiusMm: 9,
    decisionQuality: 53,
  },
  9: {
    sigmaAlongMm: 11.4,
    sigmaAcrossMm: 10.0,
    covarianceRotationDegrees: 0,
    biasXMm: 1.1,
    biasYMm: 1.6,
    outlierRate: 0.0015,
    outlierSigmaMm: 50,
    bedOffsetMm: 1.0,
    bounceOutRate: 0.02,
    deflectionRadiusMm: 8,
    decisionQuality: 60,
  },
  10: {
    sigmaAlongMm: 9.5,
    sigmaAcrossMm: 7.5,
    covarianceRotationDegrees: 0,
    biasXMm: 1.1,
    biasYMm: 1.6,
    outlierRate: 0.0012,
    outlierSigmaMm: 48,
    bedOffsetMm: 0.9,
    bounceOutRate: 0.018,
    deflectionRadiusMm: 8,
    decisionQuality: 67,
  },
  11: {
    sigmaAlongMm: 6.2,
    sigmaAcrossMm: 5.4,
    covarianceRotationDegrees: 0,
    biasXMm: 0.8,
    biasYMm: 0.8,
    outlierRate: 0.0009,
    outlierSigmaMm: 45,
    bedOffsetMm: 0.7,
    bounceOutRate: 0.015,
    deflectionRadiusMm: 7,
    decisionQuality: 73,
  },
  12: {
    sigmaAlongMm: 4.9,
    sigmaAcrossMm: 3.7,
    covarianceRotationDegrees: 0,
    biasXMm: 0.3,
    biasYMm: 0.6,
    outlierRate: 0.0006,
    outlierSigmaMm: 42,
    bedOffsetMm: 0.6,
    bounceOutRate: 0.013,
    deflectionRadiusMm: 7,
    decisionQuality: 80,
  },
  13: {
    sigmaAlongMm: 3.7,
    sigmaAcrossMm: 2.9,
    covarianceRotationDegrees: 0,
    biasXMm: 0.3,
    biasYMm: 0.6,
    outlierRate: 0.0004,
    outlierSigmaMm: 40,
    bedOffsetMm: 0.5,
    bounceOutRate: 0.011,
    deflectionRadiusMm: 6,
    decisionQuality: 87,
  },
  14: {
    sigmaAlongMm: 2.7,
    sigmaAcrossMm: 1.7,
    covarianceRotationDegrees: 0,
    biasXMm: 0.2,
    biasYMm: 0.2,
    outlierRate: 0.0002,
    outlierSigmaMm: 38,
    bedOffsetMm: 0.4,
    bounceOutRate: 0.009,
    deflectionRadiusMm: 6,
    decisionQuality: 93,
  },
  15: {
    sigmaAlongMm: 1.9,
    sigmaAcrossMm: 1.3,
    covarianceRotationDegrees: 0,
    biasXMm: 0,
    biasYMm: 0.1,
    outlierRate: 0.0001,
    outlierSigmaMm: 35,
    bedOffsetMm: 0.3,
    bounceOutRate: 0.007,
    deflectionRadiusMm: 5,
    decisionQuality: 100,
  },
};

export function skillProfileForLevel(level: number): SkillProfile {
  const clamped = Math.min(15, Math.max(1, Math.round(level)));
  const profile = LEVEL_SKILL_TABLE[clamped];
  if (!profile) {
    throw new Error(`No skill profile for level ${clamped}`);
  }
  return profile;
}
