import type { SkillProfile } from "./types";

/**
 * A hand-set prior (08-DartBot.md §D-E). Throws correct darts today; it
 * cannot yet claim to play like anything measured. Re-fitting from the D-E
 * production-data extract is a data edit to this table, not a redesign.
 */
export const LEVEL_SKILL_TABLE: Readonly<Record<number, SkillProfile>> = {
  1: {
    sigmaAlongMm: 32,
    sigmaAcrossMm: 40,
    covarianceRotationDegrees: 0,
    biasXMm: 6,
    biasYMm: 8,
    outlierRate: 0.12,
    outlierSigmaMm: 90,
    bedOffsetMm: 3.0,
    bounceOutRate: 0.05,
    deflectionRadiusMm: 12,
  },
  2: {
    sigmaAlongMm: 29,
    sigmaAcrossMm: 36,
    covarianceRotationDegrees: 0,
    biasXMm: 5,
    biasYMm: 7,
    outlierRate: 0.1,
    outlierSigmaMm: 85,
    bedOffsetMm: 2.7,
    bounceOutRate: 0.045,
    deflectionRadiusMm: 12,
  },
  3: {
    sigmaAlongMm: 26,
    sigmaAcrossMm: 32,
    covarianceRotationDegrees: 0,
    biasXMm: 5,
    biasYMm: 6,
    outlierRate: 0.09,
    outlierSigmaMm: 80,
    bedOffsetMm: 2.4,
    bounceOutRate: 0.04,
    deflectionRadiusMm: 11,
  },
  4: {
    sigmaAlongMm: 23,
    sigmaAcrossMm: 29,
    covarianceRotationDegrees: 0,
    biasXMm: 4,
    biasYMm: 6,
    outlierRate: 0.08,
    outlierSigmaMm: 75,
    bedOffsetMm: 2.1,
    bounceOutRate: 0.035,
    deflectionRadiusMm: 11,
  },
  5: {
    sigmaAlongMm: 21,
    sigmaAcrossMm: 26,
    covarianceRotationDegrees: 0,
    biasXMm: 4,
    biasYMm: 5,
    outlierRate: 0.07,
    outlierSigmaMm: 70,
    bedOffsetMm: 1.8,
    bounceOutRate: 0.03,
    deflectionRadiusMm: 10,
  },
  6: {
    sigmaAlongMm: 19,
    sigmaAcrossMm: 23,
    covarianceRotationDegrees: 0,
    biasXMm: 3,
    biasYMm: 5,
    outlierRate: 0.06,
    outlierSigmaMm: 65,
    bedOffsetMm: 1.6,
    bounceOutRate: 0.028,
    deflectionRadiusMm: 10,
  },
  7: {
    sigmaAlongMm: 17,
    sigmaAcrossMm: 21,
    covarianceRotationDegrees: 0,
    biasXMm: 3,
    biasYMm: 4,
    outlierRate: 0.055,
    outlierSigmaMm: 60,
    bedOffsetMm: 1.4,
    bounceOutRate: 0.025,
    deflectionRadiusMm: 9,
  },
  8: {
    sigmaAlongMm: 15,
    sigmaAcrossMm: 19,
    covarianceRotationDegrees: 0,
    biasXMm: 3,
    biasYMm: 4,
    outlierRate: 0.05,
    outlierSigmaMm: 55,
    bedOffsetMm: 1.2,
    bounceOutRate: 0.022,
    deflectionRadiusMm: 9,
  },
  9: {
    sigmaAlongMm: 13,
    sigmaAcrossMm: 17,
    covarianceRotationDegrees: 0,
    biasXMm: 2,
    biasYMm: 3,
    outlierRate: 0.045,
    outlierSigmaMm: 50,
    bedOffsetMm: 1.0,
    bounceOutRate: 0.02,
    deflectionRadiusMm: 8,
  },
  10: {
    sigmaAlongMm: 12,
    sigmaAcrossMm: 15,
    covarianceRotationDegrees: 0,
    biasXMm: 2,
    biasYMm: 3,
    outlierRate: 0.04,
    outlierSigmaMm: 48,
    bedOffsetMm: 0.9,
    bounceOutRate: 0.018,
    deflectionRadiusMm: 8,
  },
  11: {
    sigmaAlongMm: 10,
    sigmaAcrossMm: 13,
    covarianceRotationDegrees: 0,
    biasXMm: 2,
    biasYMm: 2,
    outlierRate: 0.035,
    outlierSigmaMm: 45,
    bedOffsetMm: 0.7,
    bounceOutRate: 0.015,
    deflectionRadiusMm: 7,
  },
  12: {
    sigmaAlongMm: 9,
    sigmaAcrossMm: 11,
    covarianceRotationDegrees: 0,
    biasXMm: 1,
    biasYMm: 2,
    outlierRate: 0.03,
    outlierSigmaMm: 42,
    bedOffsetMm: 0.6,
    bounceOutRate: 0.013,
    deflectionRadiusMm: 7,
  },
  13: {
    sigmaAlongMm: 8,
    sigmaAcrossMm: 10,
    covarianceRotationDegrees: 0,
    biasXMm: 1,
    biasYMm: 2,
    outlierRate: 0.025,
    outlierSigmaMm: 40,
    bedOffsetMm: 0.5,
    bounceOutRate: 0.011,
    deflectionRadiusMm: 6,
  },
  14: {
    sigmaAlongMm: 7,
    sigmaAcrossMm: 8,
    covarianceRotationDegrees: 0,
    biasXMm: 1,
    biasYMm: 1,
    outlierRate: 0.02,
    outlierSigmaMm: 38,
    bedOffsetMm: 0.4,
    bounceOutRate: 0.009,
    deflectionRadiusMm: 6,
  },
  15: {
    sigmaAlongMm: 6,
    sigmaAcrossMm: 7,
    covarianceRotationDegrees: 0,
    biasXMm: 0,
    biasYMm: 1,
    outlierRate: 0.015,
    outlierSigmaMm: 35,
    bedOffsetMm: 0.3,
    bounceOutRate: 0.007,
    deflectionRadiusMm: 5,
  },
};

export function skillProfileForLevel(level: number): SkillProfile {
  const clamped = Math.min(15, Math.max(1, Math.round(level)));
  const profile = LEVEL_SKILL_TABLE[clamped];
  if (!profile) {
    throw new Error(`No skill profile for level ${clamped}`);
  }
  return profile;
}
