import type { Alpine } from "alpinejs";
import { loginForm } from "@auth/login.data";
import { scoreTrainingSetup } from "@lib/game/score-training-setup.data";
import { scoreTrainingPlay } from "@lib/game/score-training-play.data";
import { fiveOhOneSetup } from "@lib/game/five-oh-one-setup.data";
import { fiveOhOnePlay } from "@lib/game/five-oh-one-play.data";
import { bobs27Setup } from "@lib/game/bobs27-setup.data";
import { bobs27Play } from "@lib/game/bobs27-play.data";
import { singlesTrainingSetup } from "@lib/game/singles-training-setup.data";
import { singlesTrainingPlay } from "@lib/game/singles-training-play.data";
import { doublesTrainingSetup } from "@lib/game/doubles-training-setup.data";
import { doublesTrainingPlay } from "@lib/game/doubles-training-play.data";
import { shanghaiSetup } from "@lib/game/shanghai-setup.data";
import { shanghaiPlay } from "@lib/game/shanghai-play.data";
import { oneTwentyOneSetup } from "@lib/game/one-twenty-one-setup.data";
import { oneTwentyOnePlay } from "@lib/game/one-twenty-one-play.data";
import { aroundTheClockSetup } from "@lib/game/around-the-clock-setup.data";
import { aroundTheClockPlay } from "@lib/game/around-the-clock-play.data";
import { tuodSetup } from "@lib/game/tuod-setup.data";
import { tuodPlay } from "@lib/game/tuod-play.data";
import { gamesIndex } from "@lib/game/games-index.data";
import { quickSubtractPlay } from "@lib/training/trivia/quick-subtract-play.data";
import { routinePlay } from "@lib/training/routines/routine-play.data";
import { routineDetail } from "@lib/training/routines/routine-detail.data";
import { trainingIndex } from "@lib/training/routines/training-index.data";
import { statisticsRoutines } from "@lib/training/routines/statistics-routines.data";
import { routineBuilder } from "@lib/training/routines/routine-builder.data";
import { schedulesIndex } from "@lib/training/schedules/schedules-index.data";
import { scheduleEditor } from "@lib/training/schedules/schedule-editor.data";
import { myScheduleForm } from "@lib/training/schedules/my-schedule.data";
import { homeWeek } from "@lib/training/schedules/home-week.data";

export function registerRouteData(Alpine: Alpine) {
  Alpine.data("loginForm", loginForm);
  Alpine.data("gamesIndex", gamesIndex);
  Alpine.data("scoreTrainingSetup", scoreTrainingSetup);
  Alpine.data("scoreTrainingPlay", scoreTrainingPlay);
  Alpine.data("fiveOhOneSetup", fiveOhOneSetup);
  Alpine.data("fiveOhOnePlay", fiveOhOnePlay);
  Alpine.data("bobs27Setup", bobs27Setup);
  Alpine.data("bobs27Play", bobs27Play);
  Alpine.data("singlesTrainingSetup", singlesTrainingSetup);
  Alpine.data("singlesTrainingPlay", singlesTrainingPlay);
  Alpine.data("doublesTrainingSetup", doublesTrainingSetup);
  Alpine.data("doublesTrainingPlay", doublesTrainingPlay);
  Alpine.data("shanghaiSetup", shanghaiSetup);
  Alpine.data("shanghaiPlay", shanghaiPlay);
  Alpine.data("oneTwentyOneSetup", oneTwentyOneSetup);
  Alpine.data("oneTwentyOnePlay", oneTwentyOnePlay);
  Alpine.data("aroundTheClockSetup", aroundTheClockSetup);
  Alpine.data("aroundTheClockPlay", aroundTheClockPlay);
  Alpine.data("tuodSetup", tuodSetup);
  Alpine.data("tuodPlay", tuodPlay);
  Alpine.data("quickSubtractPlay", quickSubtractPlay);
  Alpine.data("routinePlay", routinePlay);
  Alpine.data("routineDetail", routineDetail);
  Alpine.data("trainingIndex", trainingIndex);
  Alpine.data("statisticsRoutines", statisticsRoutines);
  Alpine.data("routineBuilder", routineBuilder);
  Alpine.data("schedulesIndex", schedulesIndex);
  Alpine.data("scheduleEditor", scheduleEditor);
  Alpine.data("myScheduleForm", myScheduleForm);
  Alpine.data("homeWeek", homeWeek);
}
