#!/usr/bin/env bash
# Test-coverage-of-changes gate (D224).
#
# THE RULE: if a change touches an executable source file under app/src/ or
# app/scripts/, the change must also touch a test that covers that file. A
# task whose diff moves behaviour without moving a single assertion is not
# finished, and this script refuses the commit rather than letting the suite's
# green stand in for a check nobody performed.
#
# It answers two questions per changed source file:
#   1. Does a covering test exist at all?
#   2. Was one of those covering tests changed in the same change set?
# A "no" to either fails, with the file and its covering tests named so the
# fix is obvious.
#
# COVERAGE IS DECIDED BY IMPORT, NOT BY FILENAME. A test covers a source file
# when it imports it — through a path alias resolved from app/tsconfig.json,
# through the mirrored path (app/src/a/b.ts <-> app/tests/a/b.test.ts), or
# through a relative specifier ending in the module's stem. Filename mirroring
# alone would have been wrong here: app/src/lib/utils/is-nav-active.ts is
# covered by app/tests/utils/is-nav-active.test.ts, off-mirror because the
# utils/ folder predates the convention (app/CLAUDE.md, "migrating from legacy
# utils/ folder"). The mirrored path is reported first because it is the
# convention; the import scan is what keeps the gate honest about the rest.
#
# EXEMPTIONS, all derived rather than listed by name, so the list cannot rot:
#   * .d.ts ambient declarations — nothing to execute.
#   * Type-only modules: no runtime export, following `export * from` chains,
#     because this repo's type-barrel convention (check-type-barrels.sh) puts
#     every shared type behind exactly such a chain. There is no runtime value
#     to assert on. A barrel that gains its first runtime export stops being
#     exempt on its own, which is the point of deriving it instead of listing
#     types.ts and interfaces.ts by name.
#   * Files generated by tooling, declared in GENERATED below with the command
#     that owns them: re-running `drizzle-kit introspect` must not demand a
#     test edit for output no human wrote.
#
# NO PER-FILE SILENCER IS PROVIDED, deliberately. A change that genuinely
# needs no new assertion still needs someone to open the covering test and
# confirm the existing ones still describe the new behaviour — and the cheapest
# honest way to record that confirmation is a touched test file. An escape
# hatch would make the gate advisory on exactly the changes it exists to
# catch. If a source file has no covering test at all, write one; that is the
# finding the gate is reporting.
#
# WHAT THIS GATE CANNOT DO, stated plainly so nobody reads its green as proof:
# it proves a covering test file was edited, never that the edit asserts
# anything. A whitespace change to the right test satisfies it. It cannot see
# whether the assertions still describe the behaviour, and it cannot catch a
# test repointed at a different input to keep it passing — root CLAUDE.md's
# test invariant carries that, and only review of the diff enforces it. What
# it does catch is the case with no defence at all today: behaviour edited and
# every test left untouched.
#
# ARGUMENTS: takes an optional list of changed paths, purely so the gate can
# be aimed at a fixture set to prove it FAILS. A gate not proven to bite is
# not a gate. With no arguments it derives the change set itself: staged files
# when a commit is in progress (pre-commit), otherwise the diff against the
# merge base with $TEST_COVERAGE_BASE_REF (default origin/main) for CI. CI
# must check out with fetch-depth: 0 or that merge base does not exist locally.

set -euo pipefail
cd "$(git rev-parse --show-toplevel 2>/dev/null || echo .)"

BASE_REF="${TEST_COVERAGE_BASE_REF:-origin/main}"

if [ "$#" -gt 0 ]; then
  CHANGED=$(printf '%s\n' "$@")
  # Fixture mode: an empty before-ref means "treat every named file as
  # changed", so a probe can be aimed at unmodified files and still exercise
  # the rule. Deriving the change set is what the two branches below do.
  BEFORE_REF=""
elif ! git diff --cached --quiet 2>/dev/null; then
  CHANGED=$(git diff --cached --name-only --diff-filter=ACMR)
  BEFORE_REF="HEAD"
else
  if git rev-parse --verify --quiet "$BASE_REF" >/dev/null; then
    MERGE_BASE=$(git merge-base "$BASE_REF" HEAD 2>/dev/null || echo "")
  else
    MERGE_BASE=""
  fi
  if [ -z "$MERGE_BASE" ]; then
    echo "OK: test-coverage — no change set to check (no staged files, no merge base with $BASE_REF)."
    exit 0
  fi
  CHANGED=$(git diff --name-only --diff-filter=ACMR "$MERGE_BASE"..HEAD)
  BEFORE_REF="$MERGE_BASE"
fi

python3 scripts/check_test_coverage.py "$CHANGED" "$BEFORE_REF"
